"""Brand-agnostic evidence models and interfaces."""

from app.brand_intelligence.models import (
    AssortmentItem,
    Brand,
    BrandDNATrait,
    BrandEvidenceDataset,
    BrandTerritoryFeature,
    Category,
    Collection,
    Color,
    Confidence,
    CraftsmanshipConstruction,
    DerivedInterpretation,
    EvidenceRecord,
    Material,
    PriceObservation,
    Product,
    Season,
    SilhouetteForm,
    SourceRecord,
)
from app.brand_intelligence.fit_models import (
    BrandFitEvaluation,
    FitDecision,
    NormalizedTrendObservation,
    TrendEvaluationInput,
    TrendEvidenceRecord,
)
from app.brand_intelligence.fit_service import evaluate_brand_fit

__all__ = [
    "AssortmentItem",
    "Brand",
    "BrandDNATrait",
    "BrandEvidenceDataset",
    "BrandTerritoryFeature",
    "Category",
    "Collection",
    "Color",
    "Confidence",
    "CraftsmanshipConstruction",
    "DerivedInterpretation",
    "EvidenceRecord",
    "Material",
    "PriceObservation",
    "Product",
    "Season",
    "SilhouetteForm",
    "SourceRecord",
    "BrandFitEvaluation",
    "FitDecision",
    "NormalizedTrendObservation",
    "TrendEvaluationInput",
    "TrendEvidenceRecord",
    "evaluate_brand_fit",
]
